### ISSUE TITLE
Effect value is number type only?

### ISSUE THREAD

**Issue by danactive** [firstCodeOutlaw/plain-rules-engine#1]
I'm trialling your library and I noticed when I add a rule with effect action of Add, the value can only be a number see line https://github.com/firstCodeOutlaw/plain-rules-engine/blob/5679088beb58bfd940913aa847b83ed010665168/src/types.ts#L17

Will you please enhance with a string type too?

Here's a code sample of my TypeScript error
```
effect: {
  action: Action.ADD,
  property: 'status',
  value: 'done' // must be a number
}
```

**Comment by danactive** [comment]
Ah looking at your code, it seems like the rules engine does not support the Add action yet

**Comment by firstCodeOutlaw** [comment]
You're right that the rule engine does not support the add action yet. Could you describe what you intend to achieve with the ADD action as if it were already implemented? I say this because the plan for ADD is to set a new key in an object based on conditions defined in a rule. I'm not sure if that aligns with your intentions.

**Comment by danactive** [comment]
@firstCodeOutlaw If the rule condition is true then the effect I want is to have the results to contain my REPLACE or ADD property `expect(results[0].status).toEqual('done');`

**Comment by firstCodeOutlaw** [comment]
@danactive A new version that addresses your concern has just been released. Effect value now takes boolean and string. I have also implemented the logic for ADD action.

https://github.com/firstCodeOutlaw/plain-rules-engine/blob/c007879c4caa81e19baa980b2a22e01ba3e4df9d/src/types.ts#L17
